MODULE SystemParameters

    IMPLICIT NONE

    INTEGER, PARAMETER :: IKIND = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: RKIND = SELECTED_REAL_KIND(15,307)
    REAL(KIND=RKIND), PARAMETER  :: ZERO=0.0, ONE=1.0
    REAL(KIND=RKIND), PARAMETER  :: TINY=1.0D-15

END MODULE SystemParameters